### ISSUE TITLE
How to log out ? and How can I check if user is login ? 

### ISSUE THREAD

**Issue by iosworkjo** [WassimBenltaief/ReactiveFB#6]
Hello 
It is nice libraray  , I want to ask about 
How can  I  log out ? and How can I check if user is login ?  
Thank you

**Comment by WassimBeltaief** [comment]
Hi @iosworkjo, Thank you. 
These features are not included in the library since the aim behind it is only to facilitate the callback style of the facebook sdk. when checking for user status or logging him out, facebook sdk did it instantly with no callbacks.
